metadataservice:
  image:
    repository: ghcr.io/metal-toolbox/hollow-metadataservice
    tag: "v0.0.26"
  # apiURL: "https://metadata-service" ## Usually the url of the metadata service itself. Output in a metadata response as "api_url"
  # phoneHomeURL: "https://phone.{{.facility}}/phone-home" ## The URL output in the metadata response as "phone_home_url". Can be a gotmpl with references to fields contained in the metadata document.
  # userStateURL: "https://userstate.{{.facility}}/user-state" ## The URL output in the metadata response as "user_state_url". Can be a gotmpl with references to fields contained in the metadata document.

shutdownGracePeriod: 10s

ingress:
  enabled: true
  hostnames:
    - metadata-service.mydomain
  publicPaths:
    - $
    - metadata
    - userdata
    - '2009-04-04'

oidc:
  audience: ""
  issuer: ""
  jwksuri: ""
  rolesClaim: ""
  userClaim: ""

lookup:
  enabled: false

  serviceURL: ""
  serviceURLFrom: {}

  oidc:
    issuer: ""
    clientID: ""
    clientSecret: ""
    audience: ""
    scopes: [] # may also be a comma or space separated string
      # - scope-one
      # - scope-two

    # # Source the variables value. See env.valueFrom for supported values
    # # Value from *From is preferred over the string variable
    # issuerFrom: {}
    # clientIDFrom:
    #   secretKeyRef:
    #     name: lookup-oidc
    #     key: client-id
    # clientSecretFrom:
    #   secretKeyRef:
    #     name: lookup-oidc
    #     key: client-secret
    # audienceFrom: {}
    # # scopes should be formatted as white space separated strings
    # scopesFrom: {}

service:
  type: ClusterIP
  annotations: {}

serviceMonitor:
  enabled: false

tracing:
  enabled: false
  # provider: ""  ## current options: "stdout", "jaeger", "otlphttp", or "otlpgrpc"
  # environment: ""
  # stdout:  ## options for stdout
  #  pretty_print:
  #  disable_timestamps:
  # jaeger: ## options for jaeger exporter
  #  agent_host:
  #  agent_port:
  #  endpoint:
  #  user:
  #  password:
  # otlp: ## options for otlpgrpc and otlphttp exporters
  #  endpoint:
  #  insecure:
  #  certificate:
  #  headers:
  #  compression:
  #  timeout:

replicaCount: 1
resources:
  limits:
    cpu: 4
    memory: 4Gi
  requests:
    cpu: 4
    memory: 4Gi
